-- =============================================================================
-- Al-Taybat — Supabase Setup Script
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- Safe to re-run: all statements use IF NOT EXISTS / OR REPLACE / ON CONFLICT
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. PROFILES TABLE
--    One row per user, mirroring auth.users.
--    Created automatically on first sign-up via the trigger below.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id               uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email            text        NOT NULL,
  name             text,
  gender           text        CHECK (gender IN ('male', 'female')),
  birth_year       integer,
  weight_kg        numeric(5, 1),
  height_cm        numeric(5, 1),
  activity_level   text        CHECK (activity_level IN ('sedentary', 'light', 'moderate', 'active')),
  health_gools_ids text,
  provider         text        NOT NULL DEFAULT 'email',
  profile_completed boolean    NOT NULL DEFAULT false,
  plan_start_date  date,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- Add plan_start_date if the table already exists without it
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS plan_start_date date;

-- Add health_gools_ids if the table already exists without it
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS health_gools_ids text;

-- ---------------------------------------------------------------------------
-- 1b. HEALTH_GOOLS TABLE (health goals catalog)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.health_gools (
  id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text        NOT NULL,
  name_en    text,
  active     boolean     NOT NULL DEFAULT true,
  image      text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.health_gools ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "health_gools: public read"       ON public.health_gools;
DROP POLICY IF EXISTS "health_gools: service_role write" ON public.health_gools;

CREATE POLICY "health_gools: public read"
  ON public.health_gools FOR SELECT
  USING (active = true);

CREATE POLICY "health_gools: service_role write"
  ON public.health_gools FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

INSERT INTO public.health_gools (id, name, name_en, active, image)
VALUES
  (1, 'تقليل الالتهاب',   'Reduce inflammation', true, 'dish'),
  (2, 'تحسين الهضم',      'Improve digestion',   true, 'dish'),
  (3, 'فقدان الوزن',      'Weight loss',         true, 'dish'),
  (4, 'تحسين الطاقة',     'Improve energy',      true, 'dish'),
  (5, 'تحسين النوم',      'Improve sleep',       true, 'dish'),
  (6, 'التخلص من التوتر', 'Reduce stress',       true, 'dish')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. TRIGGER: auto-insert a profile row when a new auth user is created
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, provider)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_app_meta_data->>'provider', 'email')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 3. TRIGGER: keep profiles.updated_at current
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 4. RLS — PROFILES
-- ---------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles: owner read"   ON public.profiles;
DROP POLICY IF EXISTS "profiles: owner update" ON public.profiles;

CREATE POLICY "profiles: owner read"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "profiles: owner update"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- ---------------------------------------------------------------------------
-- 5. USER_MEALS TABLE
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_meals (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id        uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  meal_id        integer     NOT NULL,
  meal_item_ids  text        NOT NULL DEFAULT '',
  zone_summary   integer     NOT NULL DEFAULT 1,  -- ZoneColor (1=green … 5=red)
  date           date        NOT NULL DEFAULT CURRENT_DATE,
  logged_at      timestamptz NOT NULL DEFAULT now()
);

-- Ensure user_id is uuid (if migrating from integer column)
-- ALTER TABLE public.user_meals ALTER COLUMN user_id TYPE uuid USING user_id::uuid;

ALTER TABLE public.user_meals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_meals: owner all" ON public.user_meals;
CREATE POLICY "user_meals: owner all"
  ON public.user_meals FOR ALL
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_user_meals_user_date ON public.user_meals (user_id, date DESC);

-- ---------------------------------------------------------------------------
-- 6. WEEKLY_RATINGS TABLE
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.weekly_ratings (
  id                    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id               uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period_start          date        NOT NULL,
  health_score          integer     NOT NULL CHECK (health_score BETWEEN 1 AND 5),
  adherence_score       integer     NOT NULL CHECK (adherence_score BETWEEN 1 AND 5),
  pain_reduced          boolean     NOT NULL DEFAULT false,
  energy_improved       boolean     NOT NULL DEFAULT false,
  sleep_improved        boolean     NOT NULL DEFAULT false,
  digestion_improved    boolean     NOT NULL DEFAULT false,
  mood_improved         boolean     NOT NULL DEFAULT false,
  mental_health_improved boolean    NOT NULL DEFAULT false,
  submitted_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.weekly_ratings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "weekly_ratings: owner all" ON public.weekly_ratings;
CREATE POLICY "weekly_ratings: owner all"
  ON public.weekly_ratings FOR ALL
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_weekly_ratings_user ON public.weekly_ratings (user_id, submitted_at DESC);

-- ---------------------------------------------------------------------------
-- 7. COMMUNITY_POSTS TABLE
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.community_posts (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id      uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  author_name  text        NOT NULL,
  author_avatar text,
  content      text        NOT NULL,
  image_url    text,
  love_count   integer     NOT NULL DEFAULT 0,
  is_pinned    boolean     NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "community_posts: public read" ON public.community_posts;
DROP POLICY IF EXISTS "community_posts: owner insert" ON public.community_posts;
DROP POLICY IF EXISTS "community_posts: owner delete" ON public.community_posts;

CREATE POLICY "community_posts: public read"
  ON public.community_posts FOR SELECT
  USING (true);

CREATE POLICY "community_posts: owner insert"
  ON public.community_posts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "community_posts: owner delete"
  ON public.community_posts FOR DELETE
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_community_posts_created ON public.community_posts (created_at DESC);

-- ---------------------------------------------------------------------------
-- 8. POST_REACTIONS TABLE  (user ↔ post many-to-many)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.post_reactions (
  user_id  uuid    NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  post_id  bigint  NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, post_id)
);

ALTER TABLE public.post_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "post_reactions: owner all" ON public.post_reactions;
CREATE POLICY "post_reactions: owner all"
  ON public.post_reactions FOR ALL
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 9. USER_FOLLOWS TABLE  (follower → followed)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_follows (
  follower_id  uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  followed_id  uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  PRIMARY KEY (follower_id, followed_id)
);

ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_follows: owner all"   ON public.user_follows;
DROP POLICY IF EXISTS "user_follows: public read"  ON public.user_follows;

CREATE POLICY "user_follows: owner all"
  ON public.user_follows FOR ALL
  USING (auth.uid() = follower_id);

CREATE POLICY "user_follows: public read"
  ON public.user_follows FOR SELECT
  USING (true);

-- ---------------------------------------------------------------------------
-- 10. USER_PREFERENCES TABLE
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_preferences (
  user_id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  avatar_config    jsonb,
  post_visibility  text NOT NULL DEFAULT 'public'
                       CHECK (post_visibility IN ('public', 'followers')),
  follow_permission text NOT NULL DEFAULT 'everyone'
                        CHECK (follow_permission IN ('everyone', 'approved')),
  favorite_meal_ids integer[] NOT NULL DEFAULT '{}',
  updated_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS set_user_preferences_updated_at ON public.user_preferences;
CREATE TRIGGER set_user_preferences_updated_at
  BEFORE UPDATE ON public.user_preferences
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_preferences: owner all" ON public.user_preferences;
CREATE POLICY "user_preferences: owner all"
  ON public.user_preferences FOR ALL
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 11. GRANT USAGE to authenticated role
-- ---------------------------------------------------------------------------
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
