-- =============================================================================
-- Al-Taybat — Auth & User Profile Setup
-- Covers: register, login, email verification, complete-profile
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- Safe to re-run: uses IF NOT EXISTS / OR REPLACE / ON CONFLICT DO NOTHING
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. PROFILES TABLE
--    One row per user. Created automatically by trigger on sign-up.
--    Populated progressively: sign-up fills (id, email, provider),
--    complete-profile fills the rest, sets profile_completed = true.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id                uuid        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email             text        NOT NULL,
  name              text,
  gender            text        CHECK (gender IN ('male', 'female')),
  birth_year        integer,
  weight_kg         numeric(5, 1),
  height_cm         numeric(5, 1),
  activity_level    text        CHECK (activity_level IN ('sedentary', 'light', 'moderate', 'active')),
  health_gools_ids  text,
  provider          text        NOT NULL DEFAULT 'email',
  profile_completed boolean     NOT NULL DEFAULT false,
  plan_start_date   date,                          -- set when complete-profile is saved
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- Idempotent: add plan_start_date if the table already existed without it
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS plan_start_date date;

-- Idempotent: add health_gools_ids if the table already existed without it
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS health_gools_ids text;

-- ---------------------------------------------------------------------------
-- 1b. HEALTH_GOOLS TABLE (health goals catalog)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.health_gools (
  id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text        NOT NULL,
  name_en    text,
  active     boolean     NOT NULL DEFAULT true,
  image      text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.health_gools ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "health_gools: public read"       ON public.health_gools;
DROP POLICY IF EXISTS "health_gools: service_role write" ON public.health_gools;

CREATE POLICY "health_gools: public read"
  ON public.health_gools FOR SELECT
  USING (active = true);

CREATE POLICY "health_gools: service_role write"
  ON public.health_gools FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

INSERT INTO public.health_gools (id, name, name_en, active, image)
VALUES
  (1, 'تقليل الالتهاب',   'Reduce inflammation', true, 'dish'),
  (2, 'تحسين الهضم',      'Improve digestion',   true, 'dish'),
  (3, 'فقدان الوزن',      'Weight loss',         true, 'dish'),
  (4, 'تحسين الطاقة',     'Improve energy',      true, 'dish'),
  (5, 'تحسين النوم',      'Improve sleep',       true, 'dish'),
  (6, 'التخلص من التوتر', 'Reduce stress',       true, 'dish')
ON CONFLICT (id) DO NOTHING;


-- ---------------------------------------------------------------------------
-- 2. TRIGGER: keep updated_at fresh on every UPDATE
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ---------------------------------------------------------------------------
-- 3. TRIGGER: auto-insert a minimal profile row on new user sign-up
--    Fires after Supabase creates the auth.users row (email OR OAuth).
--    ON CONFLICT DO NOTHING makes it safe for OAuth users who may trigger
--    this more than once (e.g. token refresh edge case).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, provider)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_app_meta_data->>'provider', 'email')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ---------------------------------------------------------------------------
-- 4. ROW LEVEL SECURITY
--    • Each user can only read and update their own profile row.
--    • INSERT is handled by the SECURITY DEFINER trigger above, not the app.
-- ---------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles: owner read"   ON public.profiles;
DROP POLICY IF EXISTS "profiles: owner update" ON public.profiles;
DROP POLICY IF EXISTS "profiles: owner insert" ON public.profiles;

CREATE POLICY "profiles: owner read"
  ON public.profiles
  FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "profiles: owner update"
  ON public.profiles
  FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "profiles: owner insert"
ON public.profiles
FOR INSERT
TO public
WITH CHECK (auth.uid() = id);

-- ---------------------------------------------------------------------------
-- 5. GRANTS
-- ---------------------------------------------------------------------------
GRANT USAGE  ON SCHEMA public TO authenticated;
GRANT SELECT, UPDATE ON public.profiles TO authenticated;


-- ---------------------------------------------------------------------------
-- 6. SUPABASE DASHBOARD SETTINGS (manual steps — cannot be scripted)
-- ---------------------------------------------------------------------------
-- Authentication → Providers → Email
--   ✅ Enable Email provider
--   ✅ Confirm email  (triggers the verify-email screen flow in the app)
--   ✅ Secure email change
--
-- Authentication → URL Configuration
--   Site URL:          e.g. https://your-app.com  (or exp:// for Expo Go)
--   Redirect URLs:     add your deep-link scheme, e.g. taybat://auth/callback
--
-- Authentication → Email Templates (optional — Arabic)
--   Confirm signup subject:  تأكيد تسجيلك في تطبيق الطيبات
--   Confirm signup body:     انقر الرابط أدناه لتفعيل حسابك: {{ .ConfirmationURL }}
