-- Al-Taybat production schema — reconstructed via SQL introspection of the
-- dev project (mbbbdhyhtqkxakmblzmk) on 2026-07-11, because `supabase db dump`
-- requires Docker and this environment's sandbox can't reach the Docker
-- daemon the CLI needs. Every table/column/constraint/policy/trigger/function
-- below was read directly from pg_catalog / information_schema on dev, not
-- guessed. Apply this once, in order, against a freshly created prod project.
--
-- One intentional deviation from dev: dev's `profiles` table has two
-- redundant BEFORE UPDATE triggers calling the same set_updated_at()
-- function (`set_profiles_updated_at` and `trg_profiles_updated_at`) —
-- leftover duplication from migration history. Only one is created here.

-- ============================================================================
-- 1. EXTENSIONS
-- ============================================================================
create extension if not exists pgcrypto with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists vector with schema extensions;
create extension if not exists pg_cron;

-- ============================================================================
-- 2. TABLES
-- ============================================================================

create table public.meal_item_categories (
  id integer not null primary key,
  name text not null unique,
  name_en text,
  description text,
  description_en text
);

create table public.meals (
  id integer not null primary key,
  name text not null,
  meal_item_codes text not null default '', -- CSV of meal_items.code
  zone integer not null check (zone >= 1 and zone <= 5),
  image_url text,
  meal_type_ids text not null default '',
  created_at timestamptz not null default now(),
  active boolean not null default true,
  name_en text,
  description text,
  description_en text,
  sequence integer not null default 20,
  max_day_frequency integer,
  max_week_frequency integer,
  max_month_frequency integer,
  code text not null unique, -- image filename: {public_config.meal_img_url}{code}.png
  rating numeric
);

create table public.meal_items (
  id integer not null primary key,
  name text not null,
  category integer not null default 0,
  zone integer not null check (zone >= 1 and zone <= 5),
  rating numeric,
  frequency text,
  notes text,
  image_url text,
  created_at timestamptz not null default now(),
  active boolean not null default true,
  name_en text,
  description text,
  description_en text,
  sequence integer not null default 20,
  meal_category_id integer,
  code text not null unique,
  max_day_frequency integer,
  max_week_frequency integer,
  max_month_frequency integer
);

create table public.health_goals (
  id integer generated by default as identity primary key,
  name text not null,
  name_en text,
  active boolean not null default true,
  image text,
  created_at timestamptz not null default now(),
  code text unique,
  show_in_complete_profile boolean not null default true
);

create table public.health_conditions (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null,
  name_en text,
  active boolean not null default true,
  image text,
  created_at timestamptz not null default now()
);

create table public.library_topics (
  id integer not null primary key,
  code text not null unique,
  sequence integer not null default 0,
  title text not null,
  description text not null default '',
  image_url text not null default '',
  accent_color text not null default '#10B981',
  icon text not null default 'BookOpen',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.library_topic_items (
  id integer not null primary key,
  topic_id integer not null,
  code text not null unique,
  sequence integer not null default 0,
  icon text not null default 'BookOpen',
  title text not null,
  description text not null default '',
  is_active boolean not null default true
);

create table public.membership_point_rules (
  action_key text not null primary key,
  track text not null check (track = any (array['committed','supporter'])),
  points integer not null default 0,
  description_ar text,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.membership_tiers (
  track text not null check (track = any (array['committed','supporter'])),
  tier_key text not null check (tier_key = any (array['starter','bronze','silver','gold','platinum'])),
  min_points integer not null,
  label_ar text not null,
  icon_key text not null,
  sort_order integer not null,
  primary key (track, tier_key)
);

create table public.membership_config (
  key text not null primary key,
  value text not null,
  description text,
  updated_at timestamptz not null default now()
);

create table public.public_config (
  key text not null primary key,
  value text
);

create table public.documents (
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb,
  embedding extensions.vector,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

create table public.profiles (
  id uuid not null primary key,
  email text not null,
  name text,
  gender text check (gender = any (array['male','female'])),
  birth_year integer,
  weight_kg numeric,
  height_cm numeric,
  activity_level text check (activity_level = any (array['sedentary','light','moderate','active'])),
  health_goals text[],
  provider text not null default 'email',
  profile_completed boolean not null default false,
  plan_start_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  birth_date date,
  health_goals_codes text,
  health_conditions_codes text,
  next_rating_date date,
  last_health_score integer,
  last_improvement_goals_codes text
);

create table public.user_preferences (
  user_id uuid not null primary key,
  avatar_config jsonb,
  post_visibility text not null default 'public' check (post_visibility = any (array['public','followers'])),
  follow_permission text not null default 'everyone' check (follow_permission = any (array['everyone','approved'])),
  updated_at timestamptz not null default now()
);

create table public.meal_favorites (
  user_id uuid not null,
  meal_id integer not null,
  primary key (user_id, meal_id)
);

create table public.user_meals (
  id bigint generated always as identity primary key,
  user_id uuid not null,
  meal_id integer not null,
  meal_item_codes text not null default '',
  zone_summary integer not null default 1 check (zone_summary >= 1 and zone_summary <= 5),
  datetime timestamptz not null default now(),
  date date not null default current_date,
  hungry_state integer check (hungry_state >= 1 and hungry_state <= 4) -- 1=شبعان 2=عادي 3=جائع 4=جوع شديد
);

create table public.users_ratings (
  id bigint generated always as identity primary key,
  user_id uuid not null,
  period_start date not null,
  health_score integer not null check (health_score >= 1 and health_score <= 5),
  adherence_score integer check (adherence_score >= 1 and adherence_score <= 5),
  submitted_at timestamptz not null default now(),
  improvement_goals_codes text not null default '',
  constraint uq_weekly_ratings_user_period unique (user_id, period_start)
);

create table public.community_posts (
  id bigint generated always as identity primary key,
  user_id uuid not null,
  author_name text not null,
  author_avatar text,
  content text not null,
  image_url text,
  post_type text not null default 'user_post' check (post_type = any (array['system','achievement','meal_share','user_post'])),
  is_pinned boolean not null default false,
  love_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  link_url text,
  public_notification boolean not null default false
);

create table public.post_reactions (
  user_id uuid not null,
  post_id bigint not null,
  primary key (user_id, post_id)
);

create table public.user_follows (
  follower_id uuid not null,
  target_id uuid not null,
  primary key (follower_id, target_id)
);

create table public.app_notifications (
  id bigint generated always as identity primary key,
  type text not null default 'announcement' check (type = any (array['announcement','new_post','health_tip'])),
  title text not null,
  body text not null,
  image_url text,
  action_type text,
  action_ref text,
  created_at timestamptz not null default now()
);

create table public.notification_reads (
  user_id uuid not null,
  notification_id bigint not null,
  read_at timestamptz not null default now(),
  primary key (user_id, notification_id)
);

create table public.user_point_events (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null,
  track text not null check (track = any (array['committed','supporter'])),
  action_key text not null,
  occurred_at timestamptz not null default now(),
  event_date date not null default current_date,
  reference_id uuid,
  reference_type text check (reference_type = any (array['post','meal','stat','topic'])),
  meal_ref_id bigint
);

create table public.membership_leaderboard_cache (
  track text not null check (track = any (array['committed','supporter'])),
  rank integer not null check (rank >= 1 and rank <= 100),
  user_id uuid not null,
  points integer not null,
  tier_key text not null,
  refreshed_at timestamptz not null default now(),
  primary key (track, rank)
);

-- ============================================================================
-- 3. FOREIGN KEYS
-- ============================================================================
alter table public.meal_items          add constraint meal_items_meal_category_id_fkey foreign key (meal_category_id) references public.meal_item_categories(id);
alter table public.library_topic_items add constraint library_topic_items_topic_id_fkey foreign key (topic_id) references public.library_topics(id);
alter table public.profiles            add constraint profiles_id_fkey foreign key (id) references auth.users(id);
alter table public.user_preferences    add constraint user_preferences_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.meal_favorites      add constraint meal_favorites_meal_id_fkey foreign key (meal_id) references public.meals(id);
alter table public.meal_favorites      add constraint meal_favorites_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.user_meals          add constraint user_meals_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.user_meals          add constraint user_meals_meal_id_fkey foreign key (meal_id) references public.meals(id);
alter table public.users_ratings       add constraint weekly_ratings_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.community_posts     add constraint community_posts_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.post_reactions      add constraint post_reactions_post_id_fkey foreign key (post_id) references public.community_posts(id);
alter table public.post_reactions      add constraint post_reactions_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.user_follows        add constraint user_follows_follower_id_fkey foreign key (follower_id) references auth.users(id);
alter table public.user_follows        add constraint user_follows_target_id_fkey foreign key (target_id) references auth.users(id);
alter table public.notification_reads  add constraint notification_reads_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.notification_reads  add constraint notification_reads_notification_id_fkey foreign key (notification_id) references public.app_notifications(id);
alter table public.user_point_events   add constraint user_point_events_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.user_point_events   add constraint user_point_events_action_key_fkey foreign key (action_key) references public.membership_point_rules(action_key);
alter table public.membership_leaderboard_cache add constraint membership_leaderboard_cache_user_id_fkey foreign key (user_id) references auth.users(id);

-- ============================================================================
-- 4. INDEXES (non-PK/unique ones; PK/unique indexes were created inline above)
-- ============================================================================
create index idx_app_notifications_created_at on public.app_notifications using btree (created_at desc);
create index idx_community_posts_feed on public.community_posts using btree (is_pinned desc, created_at desc);
create index documents_embedding_idx on public.documents using ivfflat (embedding extensions.vector_cosine_ops) with (lists = '100');
create index documents_metadata_idx on public.documents using gin (metadata);
create index idx_health_conditions_active on public.health_conditions using btree (active);
create index idx_library_topic_items_topic on public.library_topic_items using btree (topic_id, sequence);
create index meal_items_meal_category_id_idx on public.meal_items using btree (meal_category_id);
create index idx_user_meals_user_date on public.user_meals using btree (user_id, date desc);
create index idx_user_meals_user_datetime on public.user_meals using btree (user_id, datetime desc);
create index idx_upe_meal_ref_id on public.user_point_events using btree (user_id, meal_ref_id) where (meal_ref_id is not null);
create index idx_upe_occurred_at on public.user_point_events using btree (occurred_at);
create index idx_upe_user_track_time on public.user_point_events using btree (user_id, track, occurred_at desc);
create unique index uidx_upe_action_meal on public.user_point_events using btree (user_id, action_key, meal_ref_id) where (meal_ref_id is not null);
create unique index uidx_upe_daily_meal on public.user_point_events using btree (user_id, action_key, event_date) where (action_key = 'add_daily_meal');
create index idx_weekly_ratings_user on public.users_ratings using btree (user_id, submitted_at desc);

-- ============================================================================
-- 5. FUNCTIONS
-- ============================================================================

create or replace function public.is_admin()
 returns boolean
 language sql
 stable
 set search_path to ''
as $function$
  SELECT COALESCE(
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin',
    false
  );
$function$;

create or replace function public.set_updated_at()
 returns trigger
 language plpgsql
as $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

create or replace function public.handle_new_user()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
BEGIN
  INSERT INTO public.profiles (id, email, provider)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_app_meta_data->>'provider', 'email')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$;

create or replace function public.sync_post_love_count()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
DECLARE
  target_post_id bigint;
BEGIN
  target_post_id := COALESCE(NEW.post_id, OLD.post_id);
  UPDATE community_posts
  SET love_count = (
    SELECT COUNT(*) FROM post_reactions WHERE post_id = target_post_id
  )
  WHERE id = target_post_id;
  RETURN NULL;
END;
$function$;

create or replace function public.create_notification_from_post()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
BEGIN
  IF (
    NEW.public_notification = true AND (
      TG_OP = 'INSERT' OR
      (TG_OP = 'UPDATE' AND (OLD.public_notification IS DISTINCT FROM true))
    )
  ) THEN
    INSERT INTO app_notifications (type, title, body, action_type, action_ref)
    VALUES (
      'new_post',
      NEW.author_name,
      SUBSTRING(NEW.content FROM 1 FOR 120),
      'community_post',
      NEW.id::text
    );
  END IF;
  RETURN NEW;
END;
$function$;

create or replace function public.sync_profile_after_weekly_rating()
 returns trigger
 language plpgsql
 security definer
as $function$
begin
  update public.profiles
  set
    next_rating_date = (new.submitted_at::date + interval '7 days')::date,
    last_health_score = new.health_score,
    last_improvement_goals_codes = new.improvement_goals_codes,
    updated_at = now()
  where id = new.user_id;

  return new;
end;
$function$;

create or replace function public.record_point_event(p_track text, p_action_key text, p_reference_id uuid default null::uuid, p_reference_type text default null::text, p_meal_ref_id bigint default null::bigint)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'not authenticated';
  end if;

  if not exists (
    select 1 from membership_point_rules
    where action_key = p_action_key and track = p_track and is_active = true
  ) then return; end if;

  insert into user_point_events
    (user_id, track, action_key, event_date, reference_id, reference_type, meal_ref_id)
  values
    (v_user_id, p_track, p_action_key,
     (now() at time zone 'UTC')::date,
     p_reference_id, p_reference_type, p_meal_ref_id)
  on conflict do nothing;
end;
$function$;

create or replace function public.delete_day_point_event(p_event_date date)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  delete from user_point_events
  where user_id    = auth.uid()
    and action_key = 'add_daily_meal'
    and event_date = p_event_date;
end;
$function$;

create or replace function public.get_user_membership(p_user_id uuid)
 returns json
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_window_days          int;
  v_window_start         timestamptz;
  v_committed_points     int;
  v_supporter_points     int;
  v_committed_tier_key   text;
  v_committed_tier_label text;
  v_committed_tier_icon  text;
  v_supporter_tier_key   text;
  v_supporter_tier_label text;
  v_supporter_tier_icon  text;
begin
  select coalesce(value::int, 30) into v_window_days
    from membership_config where key = 'reset_window_days';
  v_window_start := now() - (v_window_days || ' days')::interval;

  select
    coalesce(sum(r.points) filter (where e.track = 'committed'), 0),
    coalesce(sum(r.points) filter (where e.track = 'supporter'), 0)
  into v_committed_points, v_supporter_points
  from user_point_events e
  join membership_point_rules r
    on r.action_key = e.action_key and r.is_active = true
  where e.user_id = p_user_id
    and e.occurred_at >= v_window_start;

  select t.tier_key, t.label_ar, t.icon_key
    into v_committed_tier_key, v_committed_tier_label, v_committed_tier_icon
  from membership_tiers t
  where t.track = 'committed' and t.min_points <= v_committed_points
  order by t.min_points desc limit 1;

  select t.tier_key, t.label_ar, t.icon_key
    into v_supporter_tier_key, v_supporter_tier_label, v_supporter_tier_icon
  from membership_tiers t
  where t.track = 'supporter' and t.min_points <= v_supporter_points
  order by t.min_points desc limit 1;

  v_committed_tier_key   := coalesce(v_committed_tier_key,   'starter');
  v_committed_tier_label := coalesce(v_committed_tier_label, 'مبتدئ');
  v_committed_tier_icon  := coalesce(v_committed_tier_icon,  'tier_starter');
  v_supporter_tier_key   := coalesce(v_supporter_tier_key,   'starter');
  v_supporter_tier_label := coalesce(v_supporter_tier_label, 'مبتدئ');
  v_supporter_tier_icon  := coalesce(v_supporter_tier_icon,  'tier_starter');

  return json_build_object(
    'committed_points',     v_committed_points,
    'supporter_points',     v_supporter_points,
    'committed_tier_key',   v_committed_tier_key,
    'committed_tier_label', v_committed_tier_label,
    'committed_tier_icon',  v_committed_tier_icon,
    'supporter_tier_key',   v_supporter_tier_key,
    'supporter_tier_label', v_supporter_tier_label,
    'supporter_tier_icon',  v_supporter_tier_icon,
    'window_start',         v_window_start
  );
end;
$function$;

create or replace function public.get_community_stats()
 returns table(month text, active_users bigint, avg_health_score numeric, avg_adherence_score numeric, total_meals_logged bigint)
 language sql
 stable security definer
 set search_path to ''
as $function$
  select
    to_char(date_trunc('month', wr.submitted_at), 'YYYY-MM') as month,
    count(distinct wr.user_id)                                as active_users,
    round(avg(wr.health_score)::numeric, 1)                   as avg_health_score,
    round(avg(wr.adherence_score)::numeric, 1)                as avg_adherence_score,
    count(distinct um.id)                                     as total_meals_logged
  from public.users_ratings wr
  left join public.user_meals um
    on date_trunc('month', um.datetime) = date_trunc('month', wr.submitted_at)
  group by date_trunc('month', wr.submitted_at)
  order by 1 desc;
$function$;

create or replace function public.match_documents(query_embedding extensions.vector, match_count integer default 10, filter jsonb default '{}'::jsonb)
 returns table(id bigint, content text, metadata jsonb, similarity double precision)
 language plpgsql
as $function$
#variable_conflict use_column
begin
  return query
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$function$;

create or replace function public.delete_user_account()
 returns void
 language plpgsql
 security definer
 set search_path to 'public', 'auth'
as $function$
DECLARE
  _uid uuid := auth.uid();
BEGIN
  IF _uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  DELETE FROM public.post_reactions        WHERE user_id    = _uid;
  DELETE FROM public.user_follows          WHERE follower_id = _uid OR target_id = _uid;
  DELETE FROM public.notification_reads    WHERE user_id    = _uid;
  DELETE FROM public.user_point_events     WHERE user_id    = _uid;
  DELETE FROM public.membership_leaderboard_cache WHERE user_id = _uid;
  DELETE FROM public.community_posts       WHERE user_id    = _uid;
  DELETE FROM public.meal_favorites        WHERE user_id    = _uid;
  DELETE FROM public.user_meals            WHERE user_id    = _uid;
  DELETE FROM public.users_ratings         WHERE user_id    = _uid;
  DELETE FROM public.user_preferences      WHERE user_id    = _uid;
  DELETE FROM public.profiles              WHERE id         = _uid;

  DELETE FROM auth.users WHERE id = _uid;
END;
$function$;

create or replace function public.apply_admin_policy_to_public_rls_tables()
 returns void
 language plpgsql
 security definer
 set search_path to 'pg_catalog', 'public'
as $function$
DECLARE
  table_name text;
BEGIN
  FOR table_name IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind IN ('r', 'p')
      AND c.relrowsecurity = true
  LOOP
    EXECUTE format(
      'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.%I TO authenticated',
      table_name
    );

    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON public.%I',
      'admin: full access',
      table_name
    );

    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())',
      'admin: full access',
      table_name
    );
  END LOOP;
END;
$function$;

-- ============================================================================
-- 6. TRIGGERS
-- ============================================================================
create trigger trg_profiles_updated_at before update on public.profiles for each row execute function set_updated_at();
create trigger trg_community_posts_updated_at before update on public.community_posts for each row execute function set_updated_at();
create trigger trg_user_preferences_updated_at before update on public.user_preferences for each row execute function set_updated_at();
create trigger trg_community_post_notification after insert or update of public_notification on public.community_posts for each row execute function create_notification_from_post();
create trigger trg_post_reactions_love_count after insert or delete on public.post_reactions for each row execute function sync_post_love_count();
create trigger trg_sync_profile_after_weekly_rating after insert on public.users_ratings for each row execute function sync_profile_after_weekly_rating();

-- On auth.users — creates the matching profiles row on signup
create trigger on_auth_user_created after insert on auth.users for each row execute function handle_new_user();

-- ============================================================================
-- 7. ROW LEVEL SECURITY — enable on every table
-- ============================================================================
alter table public.documents enable row level security;
alter table public.profiles enable row level security;
alter table public.meals enable row level security;
alter table public.meal_items enable row level security;
alter table public.user_preferences enable row level security;
alter table public.meal_favorites enable row level security;
alter table public.user_meals enable row level security;
alter table public.users_ratings enable row level security;
alter table public.community_posts enable row level security;
alter table public.post_reactions enable row level security;
alter table public.user_follows enable row level security;
alter table public.meal_item_categories enable row level security;
alter table public.health_goals enable row level security;
alter table public.health_conditions enable row level security;
alter table public.library_topics enable row level security;
alter table public.library_topic_items enable row level security;
alter table public.app_notifications enable row level security;
alter table public.notification_reads enable row level security;
alter table public.membership_config enable row level security;
alter table public.membership_point_rules enable row level security;
alter table public.membership_tiers enable row level security;
alter table public.user_point_events enable row level security;
alter table public.membership_leaderboard_cache enable row level security;
alter table public.public_config enable row level security;

-- ============================================================================
-- 8. RLS POLICIES (verbatim from dev — cmd/roles/qual/with_check)
-- ============================================================================

-- app_notifications
create policy "admin: full access" on public.app_notifications for all to authenticated using (is_admin()) with check (is_admin());
create policy "app_notifications_read_authenticated" on public.app_notifications for select to authenticated using (true);

-- community_posts
create policy "admin: full access" on public.community_posts for all to authenticated using (is_admin()) with check (is_admin());
create policy "community_posts: service_role all" on public.community_posts for all to service_role using (true) with check (true);
create policy "community_posts: owner delete" on public.community_posts for delete using (auth.uid() = user_id);
create policy "community_posts: owner insert" on public.community_posts for insert with check (auth.uid() = user_id);
create policy "community_posts: public read" on public.community_posts for select to anon, authenticated using (true);
create policy "community_posts: owner update" on public.community_posts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- documents
create policy "admin: full access" on public.documents for all to authenticated using (is_admin()) with check (is_admin());

-- health_conditions
create policy "health_conditions: service_role write" on public.health_conditions for all to service_role using (true) with check (true);
create policy "admin: full access" on public.health_conditions for all to authenticated using (is_admin()) with check (is_admin());
create policy "health_conditions: public read" on public.health_conditions for select using (active = true);

-- health_goals
create policy "admin: full access" on public.health_goals for all to authenticated using (is_admin()) with check (is_admin());
create policy "health_gools: service_role write" on public.health_goals for all to service_role using (true) with check (true);
create policy "health_gools: public read" on public.health_goals for select using (active = true);

-- library_topic_items
create policy "admin: full access" on public.library_topic_items for all to authenticated using (is_admin()) with check (is_admin());
create policy "library_topic_items: authenticated read" on public.library_topic_items for select to authenticated using ((is_active = true) or is_admin());
create policy "library_topic_items_read" on public.library_topic_items for select using (true);

-- library_topics
create policy "admin: full access" on public.library_topics for all to authenticated using (is_admin()) with check (is_admin());
create policy "library_topics_read" on public.library_topics for select using (true);
create policy "library_topics: authenticated read" on public.library_topics for select to authenticated using ((is_active = true) or is_admin());

-- meal_favorites
create policy "admin: full access" on public.meal_favorites for all to authenticated using (is_admin()) with check (is_admin());
create policy "meal_favorites: owner all" on public.meal_favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- meal_item_categories
create policy "admin: full access" on public.meal_item_categories for all to authenticated using (is_admin()) with check (is_admin());
create policy "Public can read meal item categories" on public.meal_item_categories for select to anon, authenticated using (true);

-- meal_items
create policy "admin: full access" on public.meal_items for all to authenticated using (is_admin()) with check (is_admin());
create policy "meal_items: service_role write" on public.meal_items for all to service_role using (true) with check (true);
create policy "meal_items: public read" on public.meal_items for select using (active = true);

-- meals
create policy "meals: service_role write" on public.meals for all to service_role using (true) with check (true);
create policy "admin: full access" on public.meals for all to authenticated using (is_admin()) with check (is_admin());
create policy "meals: public read" on public.meals for select using (active = true);

-- membership_config
create policy "admin: full access" on public.membership_config for all to authenticated using (is_admin()) with check (is_admin());
create policy "membership_config_read" on public.membership_config for select to authenticated using (true);

-- membership_leaderboard_cache
create policy "admin: full access" on public.membership_leaderboard_cache for all to authenticated using (is_admin()) with check (is_admin());
create policy "leaderboard_cache_read" on public.membership_leaderboard_cache for select to authenticated using (true);

-- membership_point_rules
create policy "admin: full access" on public.membership_point_rules for all to authenticated using (is_admin()) with check (is_admin());
create policy "membership_rules_read" on public.membership_point_rules for select to authenticated using (true);

-- membership_tiers
create policy "admin: full access" on public.membership_tiers for all to authenticated using (is_admin()) with check (is_admin());
create policy "membership_tiers_read" on public.membership_tiers for select to authenticated using (true);

-- notification_reads
create policy "notification_reads_own_all" on public.notification_reads for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "admin: full access" on public.notification_reads for all to authenticated using (is_admin()) with check (is_admin());

-- post_reactions
create policy "post_reactions: owner all" on public.post_reactions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "admin: full access" on public.post_reactions for all to authenticated using (is_admin()) with check (is_admin());

-- profiles
create policy "admin: full access" on public.profiles for all to authenticated using (is_admin()) with check (is_admin());
create policy "profiles: owner insert" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles: owner read" on public.profiles for select using (auth.uid() = id);
create policy "profiles: owner update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- public_config
create policy "public_config is readable by everyone" on public.public_config for select using (true);

-- user_follows
create policy "user_follows: owner all" on public.user_follows for all using (auth.uid() = follower_id) with check (auth.uid() = follower_id);
create policy "admin: full access" on public.user_follows for all to authenticated using (is_admin()) with check (is_admin());
create policy "user_follows: public read" on public.user_follows for select using (true);

-- user_meals
create policy "user_meals: owner all" on public.user_meals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "admin: full access" on public.user_meals for all to authenticated using (is_admin()) with check (is_admin());

-- user_point_events
create policy "admin: full access" on public.user_point_events for all to authenticated using (is_admin()) with check (is_admin());
create policy "upe_select_own" on public.user_point_events for select to authenticated using (user_id = auth.uid());

-- user_preferences
create policy "user_preferences: owner all" on public.user_preferences for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "admin: full access" on public.user_preferences for all to authenticated using (is_admin()) with check (is_admin());

-- users_ratings
create policy "weekly_ratings: owner all" on public.users_ratings for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "admin: full access" on public.users_ratings for all to authenticated using (is_admin()) with check (is_admin());

-- Safety net: explicitly (re)grants SELECT/INSERT/UPDATE/DELETE on every
-- RLS-enabled public table to `authenticated` and re-asserts the "admin:
-- full access" policy on each — belt-and-suspenders in case the new
-- project's default privileges differ from dev's.
select public.apply_admin_policy_to_public_rls_tables();

-- ============================================================================
-- 9. REALTIME
-- ============================================================================
alter publication supabase_realtime add table public.app_notifications;
alter publication supabase_realtime add table public.community_posts;

-- ============================================================================
-- 10. pg_cron JOBS
-- ============================================================================
select cron.schedule(
  'cleanup-old-notifications',
  '0 3 * * *',
  $$DELETE FROM public.app_notifications WHERE created_at < NOW() - INTERVAL '90 days'$$
);

select cron.schedule(
  'vacuum-app-notifications',
  '30 3 * * *',
  $$VACUUM ANALYZE public.app_notifications$$
);

-- ============================================================================
-- 11. STORAGE — bucket must still be created via Dashboard (Storage → New
--     bucket) or the Storage Management API; storage.buckets isn't part of
--     a schema-only migration. Recreate:
--       name: taybat_app_assets · public: true · file size limit: 1048576
--     Then compare storage.objects policies against dev's
--     `storage_policies_posts_folder` migration and mirror them.
-- ============================================================================
