export const STORAGE_KEYS = {
  LANGUAGE: 'language',
  TEMPLATE_READY: 'template_ready',
  THEME_MODE: 'theme_mode',
  COMMUNITY_REACTIONS: 'community_reactions',
  COMMUNITY_FOLLOWS: 'community_follows',
  USER_NAME: 'user_name',
  AVATAR_CONFIG: 'avatar_config',
  POST_VISIBILITY: 'post_visibility',
  FOLLOW_PERMISSION: 'follow_permission',
  MEAL_ITEM_PREFERENCES: 'meal_item_preferences',
  MEAL_FAVORITES: 'meal_favorites',
  AUTH_SESSION: '@taybat/auth_session',
  HAS_SEEN_ONBOARDING: '@taybat/has_seen_onboarding',
  MOCK_AUTH_USERS: '@taybat/mock_auth_users',
  MOCK_USER_PROFILES: '@taybat/mock_user_profiles',
} as const;
